docker_username: ds40bamo

deploy:
  host: tldr.demo.webis.de
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "4000m"

extern_environment:
  THREADS: 4
  BATCH_SIZE: 32
  CACHE_SIZE: 1000

metrics:
  - ./debug_plugin
  - ./metrics/bartscore
  - ./metrics/bert
  - ./metrics/bleu
  - ./metrics/bleurt
  - ./metrics/cider
  - ./metrics/spacy_similarity
  - ./metrics/greedy_matching
  - ./metrics/meteor
  - ./metrics/moverscore
  - source: ./metrics/rouge
    environment:
      model: "1"
  - source: ./metrics/rouge
    environment:
      model: "2"
  - source: ./metrics/rouge
    environment:
      model: "l"
  - ./metrics/sbert

summarizers:
  - ./debug_plugin
  - ./summarizers/argpagerank
  - ./summarizers/bertsum
  - ./summarizers/biasedtextrank
  - ./summarizers/conclugen
  - ./summarizers/gsum
  - ./summarizers/lobart
  - ./summarizers/longformer2roberta
  - ./summarizers/newspaper3k
  - ./summarizers/pmisum
  - ./summarizers/positionrank
  - ./summarizers/textrank
  - ./summarizers/topicrank
  - ./summarizers/featuresum
  - ./summarizers/aosumm
  - source: ./summarizers/cliffsum
    environment:
      model: MaskEnt
  - source: ./summarizers/cliffsum
    environment:
      model: MaskRel
  - source: ./summarizers/cliffsum
    environment:
      model: RegenEnt
  - source: ./summarizers/cliffsum
    environment:
      model: RegenRel
  - source: ./summarizers/cliffsum
    environment:
      model: SwapEnt
  - source: ./summarizers/cliffsum
    environment:
      model: SysLowCon
  - source: ./summarizers/coopsum
    environment:
      model: COOP-Amazon
  - source: ./summarizers/coopsum
    environment:
      model: COOP-Yelp
  - source: ./summarizers/neuralsum
    environment:
      model: T5-Base
  - source: ./summarizers/neuralsum
    environment:
      model: BART-CNN
  - source: ./summarizers/neuralsum
    environment:
      model: BART-XSum
  - source: ./summarizers/neuralsum
    environment:
      model: Pegasus-CNN
  - source: ./summarizers/neuralsum
    environment:
      model: Pegasus-XSum
  - source: ./summarizers/schnitsum
    environment:
      model: BART
  - source: ./summarizers/schnitsum
    environment:
      model: BART-65-shrinked
  - source: ./summarizers/schnitsum
    environment:
      model: BART-37-shrinked
  - source: ./summarizers/brio
    environment:
      model: CNNDM-uncased
  - source: ./summarizers/brio
    environment:
      model: CNNDM-cased
  - source: ./summarizers/brio
    environment:
      model: XSUM-cased
